apiVersion: v1
kind: ConfigMap
metadata:
  name: 02-gosec-helm-chart-override-values
  namespace: keos-core
data:
  values.yaml: |-
    ---
    gosec-authz:
      config:
        CACHE_ENABLED: "false"
        DYPLON_CACHE_ENABLED: "false"
    gosec-services-daas:
      config:
        CACHE_ENABLED: "false"
    gosec-management-baas:
      config:
        SAAS_ENABLED: "true"
    gosec-identities-daas:
      config:
        MAIL_URL: "https://${cluster_name}.${ext_domain}"
        ENV_USER_MAIL: "false"
        SMTP_HOST: "${smtp_host}"
        SMTP_USER_NAME: "${smtp_user_access_key}"
        SMTP_USER_PASSWORD: "${smtp_user_password}"
        MAIL_SENDER: "${mail_sender}"
        GET_USER_CERTIFICATE_CN: "gosec-management-baas,tenant-operator.keos-core"