apiVersion: v1
kind: ConfigMap
metadata:
  name: 02-aws-metering-helm-chart-override-values
  namespace: keos-metrics
data:
  values.yaml: |-
    awsMetering:
      extraEnvVars:
        - name: AWS_METERING_PROMETHEUS_URL
          value: "http://prometheus-operated.keos-metrics:9090/"
        - name: AWS_METERING_CUSTOMER_IDENTIFIER
          value: "${customer_id}"
        - name: AWS_METERING_INTERVAL
          value: "10m"
        - name: AWS_METERING_DYNAMODB_TABLE_NAME
          value: "${stratio_marketplace_cluster_metering_table_arn}"
        - name: AWS_METERING_DYNAMODB_TABLE_REGION
          value: "${stratio_marketplace_account_region}"
        - name: AWS_METERING_DYNAMODB_ASSUMED_ROLE_ARN
          value: "${stratio_marketplace_cluster_metering_table_iam_assumed_role_arn}"
        - name: AWS_METERING_RECONCILIATION_PERIOD_HOURS
          value: "6"
        - name: AWS_METERING_LLM_DIMENSION_ENABLED
          value: "${aws_metering_llm_dimension_enabled}"
